import * as os from "node:os";
import * as fs from "node:fs";
import * as path from "node:path";
import * as util from "node:util";
import assert from "node:assert";
import { globbySync } from "globby";
import * as prettier from "prettier";
import chalk from "chalk";

const dtsExp = /\.d\.ts$/;
const bomOptExp = /^\uFEFF?/;

const externalExp = /^([ \t]*declare module )(['"])(.+?)(\2[ \t]*{?.*)$/;
const importExp =
  /^([ \t]*(?:export )?(?:import .+? )= require\()(['"])(.+?)(\2\);.*)$/;
const importEs6Exp =
  /^([ \t]*(?:export|import) ?(?:(?:\* (?:as [^ ,]+)?)|.*)?,? ?(?:[^ ,]+ ?,?)(?:\{(?:[^ ,]+ ?,?)*\})? ?from )(['"])([^ ,]+)(\2;.*)$/;
const referenceTagExp =
  /^[ \t]*\/\/\/[ \t]*<reference[ \t]+path=(["'])(.*?)\1?[ \t]*\/>.*$/;
const identifierExp = /^\w+(?:[\.-]\w+)*$/;
const fileExp = /^([\./].*|.:.*)$/;
const privateExp = /^[ \t]*(?:static )?private (?:static )?/;
const publicExp = /^([ \t]*)(static |)(public |)(static |)(.*)/;

export interface Options {
  main: string;
  name: string;
  baseDir?: string;
  out?: string;
  newline?: string;
  indent?: string;
  outputAsModuleFolder?: boolean;
  outputAsSingleFile?: boolean; // <-- NEW OPTION ADDED
  prefix?: string;
  separator?: string;
  externals?: boolean;
  exclude?: ((file: string) => boolean) | RegExp | null;
  removeSource?: boolean;
  verbose?: boolean;
  referenceExternals?: boolean;
  emitOnIncludedFileNotFound?: boolean;
  emitOnNoIncludedFileNotFound?: boolean;
  headerPath?: string | null;
  headerText?: string;
}

export interface ModLine {
  original: string;
  modified?: string;
  skip?: boolean;
}

export interface Result {
  file: string;
  name: string;
  indent: string;
  exp: string;
  refs: string[];
  externalImports: string[];
  relativeImports: string[];
  exports: string[];
  lines: ModLine[];
  importLineRef: ModLine[];
  relativeRef: ModLine[];
  fileExists: boolean;
}

export interface BundleResult {
  fileMap: Record<string, Result>;
  includeFilesNotFound: string[];
  noIncludeFilesNotFound: string[];
  emitted?: boolean;
  options: Options;
}

function detectIndent(code: string): string | null {
  const match = code.match(/^[ \t]+/m);
  return match ? (match[0] ?? null) : null;
}

export async function bundle(options: Options): Promise<BundleResult> {
  assert(typeof options === "object" && options, "options must be an object");
  assert(options.main, 'option "main" must be defined');
  assert(options.name, 'option "name" must be defined');

  const allFiles = options.main.endsWith("**/*.d.ts");

  const main = allFiles ? "*.d.ts" : options.main;
  const exportName = options.name;
  const _baseDir = (() => {
    let baseDir = optValue(options.baseDir, path.dirname(options.main));
    if (allFiles) {
      baseDir = baseDir.slice(0, -2);
    }
    return baseDir;
  })();
  const out = optValue(options.out, exportName + ".d.ts").replace(
    /\//g,
    path.sep,
  );

  const newline = optValue(options.newline, os.EOL);
  const indent = optValue(options.indent, "    ");
  const outputAsModuleFolder = optValue(options.outputAsModuleFolder, false);
  const outputAsSingleFile = optValue(options.outputAsSingleFile, false); // <-- PARSE NEW OPTION
  const prefix = optValue(options.prefix, "");
  const separator = optValue(options.separator, "/");

  const externals = optValue(options.externals, false);
  const exclude = optValue(options.exclude, null);
  const removeSource = optValue(options.removeSource, false);
  const referenceExternals = optValue(options.referenceExternals, false);
  const emitOnIncludedFileNotFound = optValue(
    options.emitOnIncludedFileNotFound,
    false,
  );
  const emitOnNoIncludedFileNotFound = optValue(
    options.emitOnNoIncludedFileNotFound,
    false,
  );
  const _headerPath = optValue(options.headerPath, null);
  const headerText = optValue(options.headerText, "");

  const comments = false;
  const verbose = optValue(options.verbose, false);

  assert(typeof newline === "string", 'option "newline" must be a string');
  assert(typeof indent === "string", 'option "indent" must be a string');
  assert(typeof prefix === "string", 'option "prefix" must be a string');
  assert(separator.length > 0, 'option "separator" must have non-zero length');

  const baseDir = path.resolve(_baseDir);
  let mainFile = allFiles
    ? path.resolve(baseDir, "**/*.d.ts")
    : path.resolve(main.replace(/\//g, path.sep));
  const outFile = calcOutFilePath(out, baseDir);

  let headerData = "// GENERATED BY SSE BUILDER" + newline + newline;
  const headerPath =
    _headerPath && _headerPath !== "none"
      ? path.resolve(_headerPath.replace(/\//g, path.sep))
      : _headerPath;

  trace("### settings object passed ###");
  traceObject(options);

  if (!allFiles) {
    assert(fs.existsSync(mainFile), "main does not exist: " + mainFile);
  }

  if (headerPath) {
    if (headerPath === "none") {
      headerData = "";
    } else {
      assert(fs.existsSync(headerPath), "header does not exist: " + headerPath);
      headerData = fs.readFileSync(headerPath, "utf8") + headerData;
    }
  } else if (headerText) {
    headerData = "/*" + headerText + "*/\n";
  }

  let isExclude: (file: string, arg?: boolean) => boolean;
  if (typeof exclude === "function") {
    isExclude = exclude as (file: string) => boolean;
  } else if (exclude instanceof RegExp) {
    isExclude = (file: string) => exclude.test(file);
  } else {
    isExclude = () => false;
  }

  const sourceTypings = globbySync("**/*.d.ts", { cwd: baseDir }).map((file) =>
    path.resolve(baseDir, file),
  );

  if (allFiles) {
    let mainFileContent = "";
    trace("## temporally main file ##");
    sourceTypings.forEach((file) => {
      let generatedLine =
        "export * from './" +
        path.relative(baseDir, file.slice(0, -5)).replace(path.sep, "/") +
        "';";
      trace(generatedLine);
      mainFileContent += generatedLine + "\n";
    });
    mainFile = path.resolve(baseDir, "dts-bundle.tmp." + exportName + ".d.ts");
    fs.writeFileSync(mainFile, mainFileContent, "utf8");
  }

  trace("\n### find typings ###");

  const inSourceTypings = (file: string) => {
    return (
      sourceTypings.indexOf(file) !== -1 ||
      sourceTypings.indexOf(path.join(file, "index.d.ts")) !== -1
    );
  };

  let fileMap: Record<string, Result> = Object.create(null);
  let globalExternalImports: string[] = [];
  let mainParse: Result | undefined;
  let externalTypings: string[] = [];
  let inExternalTypings = (file: string) =>
    externalTypings.indexOf(file) !== -1;
  {
    trace("\n### parse files ###");

    let queue: string[] = [mainFile];
    let queueSeen: Record<string, boolean> = Object.create(null);

    while (queue.length > 0) {
      let target = queue.shift();
      if (!target) continue;

      if (queueSeen[target]) {
        continue;
      }
      queueSeen[target] = true;

      let parse = parseFile(target);
      if (!mainParse) {
        mainParse = parse;
      }
      fileMap[parse.file] = parse;
      pushUniqueArr(queue, parse.refs, parse.relativeImports);
    }
  }

  trace("\n### map exports ###");

  let exportMap: Record<string, Result> = Object.create(null);
  Object.keys(fileMap).forEach((file) => {
    let parse = fileMap[file];
    if (!parse) return;

    parse.exports.forEach((name) => {
      assert(!(name in exportMap), "already got export for: " + name);
      exportMap[name] = parse as Result;
      trace("- %s -> %s", name, (parse as Result).file);
    });
  });

  trace("\n### determine typings to include ###");

  let excludedTypings: string[] = [];
  let usedTypings: Result[] = [];
  let externalDependencies: string[] = [];
  {
    let queue: Result[] = mainParse ? [mainParse] : [];
    let queueSeen: Record<string, boolean> = Object.create(null);

    while (queue.length > 0) {
      let parse = queue.shift();
      if (!parse) continue;

      if (queueSeen[parse.file]) {
        continue;
      }
      queueSeen[parse.file] = true;

      usedTypings.push(parse);

      parse.externalImports.forEach((name) => {
        let p = exportMap[name];
        if (!externals) {
          pushUnique(externalDependencies, !p ? name : p.file);
          return;
        }

        if (!p) {
          warning(" X - Missing external module %s", name);
          return;
        }

        if (isExclude(path.relative(baseDir, p.file), true)) {
          pushUnique(excludedTypings, p.file);
          return;
        }
        queue.push(p);
      });

      parse.relativeImports.forEach((file) => {
        let p = fileMap[file];
        if (!p) {
          warning(" X - Missing relative module %s", file);
          return;
        }

        if (isExclude(path.relative(baseDir, p.file), false)) {
          pushUnique(excludedTypings, p.file);
          return;
        }
        queue.push(p);
      });
    }
  }

  trace("\n### rewrite global external modules ###");

  usedTypings.forEach((parse) => {
    parse.relativeRef.forEach((line) => {
      if (outputAsSingleFile) return; // <-- PRESERVE EXTERNALS FOR SINGLE FILE
      line.modified = replaceExternal(line.original, getLibName);
    });

    parse.importLineRef.forEach((line) => {
      if (outputAsModuleFolder || outputAsSingleFile) {
        // <-- AVOID REWRITING IMPORTS FOR SINGLE FILE
        if (outputAsModuleFolder) {
          line.skip = true;
        }
        return;
      }

      if (importExp.test(line.original)) {
        line.modified = replaceImportExport(line.original, getLibName);
      } else {
        line.modified = replaceImportExportEs6(line.original, getLibName);
      }
    });
  });

  trace("\n### build output ###");

  let content = headerData;
  if (externalDependencies.length > 0) {
    content += "// Dependencies for this module:" + newline;
    externalDependencies.forEach((file) => {
      if (referenceExternals) {
        content +=
          formatReference(path.relative(baseDir, file).replace(/\\/g, "/")) +
          newline;
      } else {
        content +=
          "//   " + path.relative(baseDir, file).replace(/\\/g, "/") + newline;
      }
    });
  }

  if (globalExternalImports.length > 0) {
    content += newline;
    content += globalExternalImports.join(newline) + newline;
  }

  content += newline;

  content +=
    usedTypings
      .filter((parse: Result) => {
        parse.lines = parse.lines.filter((line: ModLine) => {
          return true !== line.skip;
        });
        return parse.lines.length > 0;
      })
      .map((parse: Result) => {
        if (inSourceTypings(parse.file)) {
          return formatModule(
            parse.file,
            parse.lines.map((line) => {
              return getIndenter(parse.indent, indent)(line);
            }),
          );
        } else {
          return (
            parse.lines
              .map((line) => {
                return getIndenter(parse.indent, indent)(line);
              })
              .join(newline) + newline
          );
        }
      })
      .join(newline) + newline;

  if (removeSource) {
    sourceTypings.forEach((p) => {
      if (p !== outFile && dtsExp.test(p) && fs.statSync(p).isFile()) {
        fs.unlinkSync(p);
      }
    });
  }

  let inUsed = (file: string): boolean => {
    return usedTypings.some((parse) => parse.file === file);
  };

  let bundleResult: BundleResult = {
    fileMap,
    includeFilesNotFound: [],
    noIncludeFilesNotFound: [],
    options,
  };

  for (let p in fileMap) {
    let parse = fileMap[p];
    if (parse && !parse.fileExists) {
      if (inUsed(parse.file)) {
        bundleResult.includeFilesNotFound.push(parse.file);
        warning(" X Included file NOT FOUND %s ", parse.file);
      } else {
        bundleResult.noIncludeFilesNotFound.push(parse.file);
      }
    }
  }

  trace("\n### write output ###");
  if (
    (bundleResult.includeFilesNotFound.length == 0 ||
      (bundleResult.includeFilesNotFound.length > 0 &&
        emitOnIncludedFileNotFound)) &&
    (bundleResult.noIncludeFilesNotFound.length == 0 ||
      (bundleResult.noIncludeFilesNotFound.length > 0 &&
        emitOnNoIncludedFileNotFound))
  ) {
    {
      let outDir = path.dirname(outFile);
      if (!fs.existsSync(outDir)) {
        fs.mkdirSync(outDir, { recursive: true });
      }
    }

    try {
      const formattedContent = await prettier.format(content, {
        parser: "typescript",
        printWidth: 80,
        tabWidth: 2,
        singleQuote: false,
        trailingComma: "all",
      });

      fs.writeFileSync(outFile, formattedContent, "utf8");
    } catch (formatError) {
      warning(
        " XXX Failed to format output with Prettier. Writing unformatted.",
      );
      fs.writeFileSync(outFile, content, "utf8");
    }

    bundleResult.emitted = true;
  } else {
    warning(" XXX Not emit due to exist files not found.");
    bundleResult.emitted = false;
  }

  if (allFiles) {
    fs.unlinkSync(mainFile);
  }
  return bundleResult;

  function calcOutFilePath(outPath: string, baseDir: string) {
    let result = path.resolve(baseDir, outPath);
    if (outPath.startsWith("~" + path.sep)) {
      result = path.resolve(".", outPath.slice(2));
    }
    return result;
  }

  function traceObject(obj: unknown) {
    if (verbose) console.dir(obj, { colors: true });
  }

  function trace(...args: unknown[]) {
    if (verbose) console.log(chalk.gray(util.format.apply(null, args as any)));
  }

  function warning(...args: unknown[]) {
    console.log(chalk.yellow(util.format.apply(null, args as any)));
  }

  function getModName(file: string) {
    return path.relative(
      baseDir,
      path.dirname(file) +
        path.sep +
        path.basename(file).replace(/\.d\.ts$/, ""),
    );
  }

  function getExpName(file: string) {
    if (file === mainFile) return exportName;
    return getExpNameRaw(file);
  }

  function getExpNameRaw(file: string) {
    return prefix + exportName + separator + cleanupName(getModName(file));
  }

  function getLibName(ref: string) {
    return getExpNameRaw(mainFile) + separator + prefix + separator + ref;
  }

  function cleanupName(name: string) {
    return name.replace(/\.\./g, "--").replace(/[\\\/]/g, separator);
  }

  function mergeModulesLines(lines: string[]) {
    // <-- REMOVE INDENT IF SINGLE FILE
    const i = outputAsModuleFolder || outputAsSingleFile ? "" : indent;
    return (lines.length === 0 ? "" : i + lines.join(newline + i)) + newline;
  }

  function formatModule(file: string, lines: string[]) {
    let out = "";
    // <-- SKIP WRAPPING WITH `declare module` IF SINGLE FILE
    if (outputAsModuleFolder || outputAsSingleFile)
      return mergeModulesLines(lines);

    out += "declare module '" + getExpName(file) + "' {" + newline;
    out += mergeModulesLines(lines);
    out += "}" + newline;
    return out;
  }

  function parseFile(file: string): Result {
    const name = getModName(file);

    const res: Result = {
      file: file,
      name: name,
      indent: indent,
      exp: getExpName(file),
      refs: [],
      externalImports: [],
      relativeImports: [],
      exports: [],
      lines: [],
      fileExists: true,
      importLineRef: [],
      relativeRef: [],
    };

    if (!fs.existsSync(file)) {
      res.fileExists = false;
      return res;
    }
    if (fs.lstatSync(file).isDirectory()) {
      file = path.join(file, "index.d.ts");
    }
    const code = fs
      .readFileSync(file, "utf8")
      .replace(bomOptExp, "")
      .replace(/\s*$/, "");

    res.indent = detectIndent(code) ?? indent;

    let multiComment: string[] = [];
    let queuedJSDoc: string[] | null = null;
    let inBlockComment = false;

    const popBlock = () => {
      if (multiComment.length > 0) {
        if (/^[ \t]*\/\*\*/.test(multiComment[0] ?? "")) {
          queuedJSDoc = multiComment;
        } else if (comments) {
          multiComment.forEach((line) => res.lines.push({ original: line }));
        }
        multiComment = [];
      }
      inBlockComment = false;
    };

    const popJSDoc = () => {
      if (queuedJSDoc) {
        queuedJSDoc.forEach((line) => {
          let match = line.match(/^([ \t]*)(\*.*)/);
          if (match && match[1] !== undefined && match[2] !== undefined) {
            res.lines.push({ original: match[1] + " " + match[2] });
          } else {
            res.lines.push({ original: line });
          }
        });
        queuedJSDoc = null;
      }
    };

    code.split(/\r?\n/g).forEach((line: string) => {
      if (/^[((=====)(=*)) \t]*\*+\//.test(line)) {
        multiComment.push(line);
        popBlock();
        return;
      }

      if (/^[ \t]*\/\*/.test(line)) {
        multiComment.push(line);
        inBlockComment = true;
        if (/\*+\/[ \t]*$/.test(line)) {
          popBlock();
        }
        return;
      }

      if (inBlockComment) {
        multiComment.push(line);
        return;
      }

      if (/^\s*$/.test(line)) {
        res.lines.push({ original: "" });
        return;
      }

      if (/^\/\/\//.test(line)) {
        let ref = extractReference(line);
        if (ref) {
          let refPath = path.resolve(path.dirname(file), ref);
          if (!inSourceTypings(refPath)) {
            if (!inExternalTypings(refPath)) {
              externalTypings.push(refPath);
            }
          }
          pushUnique(res.refs, refPath);
          return;
        }
      }

      if (/^\/\//.test(line)) {
        if (comments) {
          res.lines.push({ original: line });
        }
        return;
      }

      if (privateExp.test(line)) {
        queuedJSDoc = null;
        return;
      }
      popJSDoc();

      let importMatch =
        line.indexOf("from") >= 0 ? line.match(importEs6Exp) : null;
      if (!importMatch && line.indexOf("require") >= 0) {
        importMatch = line.match(importExp);
      }

      if (
        importMatch &&
        importMatch[1] !== undefined &&
        importMatch[2] !== undefined &&
        importMatch[3] !== undefined &&
        importMatch[4] !== undefined
      ) {
        const lead = importMatch[1];
        const quote = importMatch[2];
        const moduleName = importMatch[3];
        const trail = importMatch[4];

        const impPath = path.resolve(path.dirname(file), moduleName);

        if (fileExp.test(moduleName)) {
          let modLine: ModLine = {
            original: lead + quote + getExpName(impPath) + trail,
            skip: outputAsSingleFile, // <-- STRIP INTERNAL IMPORTS FOR SINGLE FILE
          };
          res.lines.push(modLine);

          let full = path.resolve(path.dirname(file), impPath);
          if (!fs.existsSync(full) || fs.existsSync(full + ".d.ts")) {
            full += ".d.ts";
          }
          pushUnique(res.relativeImports, full);
          res.importLineRef.push(modLine);
        } else {
          let modLine: ModLine = { original: line };
          pushUnique(res.externalImports, moduleName);
          if (externals) {
            res.importLineRef.push(modLine);
          }
          if (!outputAsModuleFolder) {
            res.lines.push(modLine);
          } else {
            pushUnique(globalExternalImports, line);
          }
        }
      } else {
        let extMatch = line.match(externalExp);
        if (extMatch && extMatch[3] !== undefined) {
          const moduleName = extMatch[3];
          pushUnique(res.exports, moduleName);
          let modLine: ModLine = { original: line };
          res.relativeRef.push(modLine);
          res.lines.push(modLine);
        } else {
          let pubMatch = line.match(publicExp);
          if (pubMatch) {
            const sp = pubMatch[1] ?? "";
            const static1 = pubMatch[2] ?? "";
            const static2 = pubMatch[4] ?? "";
            const ident = pubMatch[5] ?? "";
            line = sp + static1 + static2 + ident;
          }

          if (inSourceTypings(file)) {
            res.lines.push({
              original: line.replace(/^(export )?declare /g, "$1"),
            });
          } else {
            res.lines.push({ original: line });
          }
        }
      }
    });

    return res;
  }
}

function pushUnique<T>(arr: T[], value: T) {
  if (arr.indexOf(value) < 0) {
    arr.push(value);
  }
  return arr;
}

function pushUniqueArr<T>(arr: T[], ...values: T[][]) {
  values.forEach((vs) => vs.forEach((v) => pushUnique(arr, v)));
  return arr;
}

function formatReference(file: string) {
  return '/// <reference path="' + file.replace(/\\/g, "/") + '" />';
}

function extractReference(tag: string) {
  let match = tag.match(referenceTagExp);
  if (match && match[2] !== undefined) {
    return match[2];
  }
  return null;
}

function replaceImportExport(line: string, replacer: (str: string) => string) {
  let match = line.match(importExp);
  if (
    match &&
    match[1] !== undefined &&
    match[2] !== undefined &&
    match[3] !== undefined &&
    match[4] !== undefined
  ) {
    const lead = match[1];
    const quote = match[2];
    const moduleName = match[3];
    const trail = match[4];
    if (identifierExp.test(moduleName)) {
      return lead + quote + replacer(moduleName) + trail;
    }
  }
  return line;
}

function replaceImportExportEs6(
  line: string,
  replacer: (str: string) => string,
) {
  if (line.indexOf("from") < 0) return line;

  let match = line.match(importEs6Exp);
  if (
    match &&
    match[1] !== undefined &&
    match[2] !== undefined &&
    match[3] !== undefined &&
    match[4] !== undefined
  ) {
    const lead = match[1];
    const quote = match[2];
    const moduleName = match[3];
    const trail = match[4];
    if (identifierExp.test(moduleName)) {
      return lead + quote + replacer(moduleName) + trail;
    }
  }
  return line;
}

function replaceExternal(line: string, replacer: (str: string) => string) {
  let match = line.match(externalExp);
  if (
    match &&
    match[1] !== undefined &&
    match[2] !== undefined &&
    match[3] !== undefined &&
    match[4] !== undefined
  ) {
    const declareModule = match[1];
    const beforeIndent = match[2];
    const moduleName = match[3];
    const afterIdent = match[4];
    if (identifierExp.test(moduleName)) {
      return declareModule + beforeIndent + replacer(moduleName) + afterIdent;
    }
  }
  return line;
}

function getIndenter(actual: string, use: string): (line: ModLine) => string {
  if (actual === use || !actual) {
    return (line) => line.modified ?? line.original;
  }
  return (line) =>
    (line.modified ?? line.original).replace(
      new RegExp("^" + actual + "+", "g"),
      (match) => match.split(actual).join(use),
    );
}

function optValue<T>(passed: T | undefined | null, def: T): T {
  if (passed === undefined || passed === null) {
    return def;
  }
  return passed;
}
